% -------------------------------------------------------------------
%  Generated by MATLAB on 15-Jun-2021 12:13:48
%  MATLAB version: 9.7.0.1471314 (R2019b) Update 7
% -------------------------------------------------------------------
                               

IDT_ButtonStatus = Simulink.AliasType;
IDT_ButtonStatus.Description = '';
IDT_ButtonStatus.DataScope = 'Auto';
IDT_ButtonStatus.HeaderFile = 'Rte_Type.h';
IDT_ButtonStatus.BaseType = 'boolean';

IDT_SeatStatus = Simulink.AliasType;
IDT_SeatStatus.Description = '';
IDT_SeatStatus.DataScope = 'Auto';
IDT_SeatStatus.HeaderFile = 'Rte_Type.h';
IDT_SeatStatus.BaseType = 'boolean';

IDT_Temperature = Simulink.AliasType;
IDT_Temperature.Description = '';
IDT_Temperature.DataScope = 'Auto';
IDT_Temperature.HeaderFile = 'Rte_Type.h';
IDT_Temperature.BaseType = 'uint8';

P_IDT_ButtonStatus = Simulink.Parameter;
P_IDT_ButtonStatus.Value = 0;
P_IDT_ButtonStatus.CoderInfo.StorageClass = 'Auto';
P_IDT_ButtonStatus.Description = '';
P_IDT_ButtonStatus.DataType = 'IDT_ButtonStatus';
P_IDT_ButtonStatus.Min = [];
P_IDT_ButtonStatus.Max = [];
P_IDT_ButtonStatus.DocUnits = '';

P_IDT_Temperature = Simulink.Parameter;
P_IDT_Temperature.Value = 0;
P_IDT_Temperature.CoderInfo.StorageClass = 'Auto';
P_IDT_Temperature.Description = '';
P_IDT_Temperature.DataType = 'IDT_Temperature';
P_IDT_Temperature.Min = [];
P_IDT_Temperature.Max = [];
P_IDT_Temperature.DocUnits = '';

SystemActive = Simulink.Signal;
SystemActive.DataType = 'boolean';
SystemActive.CoderInfo.StorageClass = 'ExportedGlobal';

TemperatureRanges_Low = AUTOSAR.Parameter;
TemperatureRanges_Low.Value = 30;
TemperatureRanges_Low.CoderInfo.StorageClass = 'Custom';
TemperatureRanges_Low.CoderInfo.Alias = '';
TemperatureRanges_Low.CoderInfo.Alignment = -1;
TemperatureRanges_Low.CoderInfo.CustomStorageClass = ...
  'CalPrm';
TemperatureRanges_Low.CoderInfo.CustomAttributes.HeaderFile = '';
TemperatureRanges_Low.CoderInfo.CustomAttributes.ElementName = ...
  'TemperatureStage1';
TemperatureRanges_Low.CoderInfo.CustomAttributes.PortName = ...
  'TemperatureRanges';
TemperatureRanges_Low.CoderInfo.CustomAttributes.InterfacePath = ...
  '/Interfaces/IF_TemperatureValues';
TemperatureRanges_Low.CoderInfo.CustomAttributes.CalibrationComponent = '';
TemperatureRanges_Low.CoderInfo.CustomAttributes.ProviderPortName = '';
TemperatureRanges_Low.Description = '';
TemperatureRanges_Low.DataType = 'IDT_Temperature';
TemperatureRanges_Low.Min = [];
TemperatureRanges_Low.Max = [];
TemperatureRanges_Low.DocUnits = '';
TemperatureRanges_Low.SwCalibrationAccess = 'ReadWrite';
TemperatureRanges_Low.DisplayFormat = '';

TemperatureRanges_Medium = AUTOSAR.Parameter;
TemperatureRanges_Medium.Value = 35;
TemperatureRanges_Medium.CoderInfo.StorageClass = 'Custom';
TemperatureRanges_Medium.CoderInfo.Alias = '';
TemperatureRanges_Medium.CoderInfo.Alignment = -1;
TemperatureRanges_Medium.CoderInfo.CustomStorageClass = ...
  'CalPrm';
TemperatureRanges_Medium.CoderInfo.CustomAttributes.HeaderFile = '';
TemperatureRanges_Medium.CoderInfo.CustomAttributes.ElementName = ...
  'TemperatureStage2';
TemperatureRanges_Medium.CoderInfo.CustomAttributes.PortName = ...
  'TemperatureRanges';
TemperatureRanges_Medium.CoderInfo.CustomAttributes.InterfacePath = ...
  '/Interfaces/IF_TemperatureValues';
TemperatureRanges_Medium.CoderInfo.CustomAttributes.CalibrationComponent = '';
TemperatureRanges_Medium.CoderInfo.CustomAttributes.ProviderPortName = '';
TemperatureRanges_Medium.Description = '';
TemperatureRanges_Medium.DataType = 'IDT_Temperature';
TemperatureRanges_Medium.Min = [];
TemperatureRanges_Medium.Max = [];
TemperatureRanges_Medium.DocUnits = '';
TemperatureRanges_Medium.SwCalibrationAccess = 'ReadWrite';
TemperatureRanges_Medium.DisplayFormat = '';

TemperatureRanges_High = AUTOSAR.Parameter;
TemperatureRanges_High.Value = 45;
TemperatureRanges_High.CoderInfo.StorageClass = 'Custom';
TemperatureRanges_High.CoderInfo.Alias = '';
TemperatureRanges_High.CoderInfo.Alignment = -1;
TemperatureRanges_High.CoderInfo.CustomStorageClass = ...
  'CalPrm';
TemperatureRanges_High.CoderInfo.CustomAttributes.HeaderFile = '';
TemperatureRanges_High.CoderInfo.CustomAttributes.ElementName = ...
  'TemperatureStage3';
TemperatureRanges_High.CoderInfo.CustomAttributes.PortName = ...
  'TemperatureRanges';
TemperatureRanges_High.CoderInfo.CustomAttributes.InterfacePath = ...
  '/Interfaces/IF_TemperatureValues';
TemperatureRanges_High.CoderInfo.CustomAttributes.CalibrationComponent = '';
TemperatureRanges_High.CoderInfo.CustomAttributes.ProviderPortName = '';
TemperatureRanges_High.Description = '';
TemperatureRanges_High.DataType = 'IDT_Temperature';
TemperatureRanges_High.Min = [];
TemperatureRanges_High.Max = [];
TemperatureRanges_High.DocUnits = '';
TemperatureRanges_High.SwCalibrationAccess = 'ReadWrite';
TemperatureRanges_High.DisplayFormat = '';

RTE_OK = Simulink.Parameter;
RTE_OK.Value = 0;
RTE_OK.CoderInfo.StorageClass = 'Custom';
RTE_OK.CoderInfo.CustomStorageClass = 'Define';
RTE_OK.Description = '';
RTE_OK.DataType = 'boolean';
RTE_OK.Min = 0;
RTE_OK.Max = 1;
%P_IDT_ButtonStatus.DocUnits = '';

try
    seat_heating_control_defineIntEnumTypes
end
