name: Test model with BTC and Matlab in Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-docker:
    runs-on: self-hosted
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '#test') }}

    steps:
    - uses: actions/checkout@v3

    - name: Build docker image
      # shell: powershell
      # run: |
      #   $env:ML_LIC_CONTENT | Out-File -FilePath "${{github.workspace}}/docker/matlab.lic" -Encoding UTF8
      #   $env:BTC_LIC_CONTENT | Out-File -FilePath "${{github.workspace}}/docker/btc.lic" -Encoding UTF8
      #   docker build -t ep-ml:24.2_23b docker
      run: |
        echo "$ML_LIC_CONTENT" > "${GITHUB_WORKSPACE}/docker/matlab.lic"
        echo "$BTC_LIC_CONTENT" > "${GITHUB_WORKSPACE}/docker/btc.lic"
        docker build -t ep-ml:24.2_23b docker

      env:
        ML_LIC_CONTENT: ${{ secrets.ML_LICENSE }}
        BTC_LIC_CONTENT: ${{ secrets.BTC_LICENSE }}

    - name: Run tests (docker/linux)
      run: |
        docker run --rm --mac-address 02:42:ac:11:13:37 \
            --volume "${{github.workspace}}:/workdir" \
            --workdir "/workdir" \
            ep-ml:24.2_23b \
            python3 test/run_tests.py

    - name: Publish test results to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: model/reports
